In [3]:
import torch

In [4]:
x = torch.empty(5, 3 )
print(x)

tensor([[ 8.2729e+34,  4.5451e-41, -3.7610e+27],
        [ 3.2586e-41, -3.7585e+27,  3.2586e-41],
        [-4.2453e+27,  3.2586e-41,  0.0000e+00],
        [ 0.0000e+00, -3.7562e+27,  3.2586e-41],
        [-6.5550e+26,  3.2586e-41, -2.9300e-33]])


In [5]:
x = torch.zeros(2 ,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [6]:
x = torch.ones(2 ,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [7]:
x = torch.ones(2 ,2 , dtype=torch.int)
print(x)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)


In [8]:
x = torch.tensor([2.5 ,2.8])
print(x)

tensor([2.5000, 2.8000])


In [9]:
x = torch.rand(3,2)
print(x)

tensor([[0.6163, 0.5688],
        [0.2773, 0.2383],
        [0.6062, 0.6499]])


In [10]:
y = torch.rand(3 ,2)
print(y)

tensor([[0.3504, 0.9366],
        [0.2419, 0.0673],
        [0.8775, 0.2186]])


In [11]:
print(x + y)

tensor([[0.9667, 1.5054],
        [0.5192, 0.3056],
        [1.4837, 0.8685]])


In [12]:
x.add(y)

tensor([[0.9667, 1.5054],
        [0.5192, 0.3056],
        [1.4837, 0.8685]])

In [13]:
z = torch.mul(x , y)
print(z)

tensor([[0.2159, 0.5327],
        [0.0671, 0.0160],
        [0.5319, 0.1421]])


In [14]:
z = torch.div(x , y)
print(z)

tensor([[1.7590, 0.6073],
        [1.1466, 3.5384],
        [0.6908, 2.9729]])


In [15]:
print(z.size())

torch.Size([3, 2])


In [16]:
print(z[1 ,: ])

tensor([1.1466, 3.5384])


In [17]:
y = x.view(6)
print(y)

tensor([0.6163, 0.5688, 0.2773, 0.2383, 0.6062, 0.6499])


In [18]:
y = x.view(-1 , 3)
print(y)
print(y.size())

tensor([[0.6163, 0.5688, 0.2773],
        [0.2383, 0.6062, 0.6499]])
torch.Size([2, 3])


In [19]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [20]:
import numpy as np
b = a.numpy()
print(b)
a.add_(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [21]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [22]:
x = torch.ones(5 , requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


In [23]:
## Back propagation
x = torch.randn(3, requires_grad=True)
print(x)
y = x + 2
print(y)
z = y * y * 2
print(z)
 # z = z.mean() # mean Operation
print(z)
# z.backward()  # Gradient od z w.r.t x,  (dz/dx)
# print(x.grad)
vector = torch.tensor([0.1 , 1.0 , 0.001] , dtype=torch.float)
print(vector)
z.backward(vector)
print(x.grad)

tensor([ 0.3787, -0.9740, -1.0835], requires_grad=True)
tensor([2.3787, 1.0260, 0.9165], grad_fn=<AddBackward0>)
tensor([11.3161,  2.1053,  1.6800], grad_fn=<MulBackward0>)
tensor([11.3161,  2.1053,  1.6800], grad_fn=<MulBackward0>)
tensor([0.1000, 1.0000, 0.0010])
tensor([9.5147e-01, 4.1039e+00, 3.6661e-03])


In [24]:
x.requires_grad_(False)
x.detach()
with torch.no_grad():
      y = x + 2
      print(y)

tensor([2.3787, 1.0260, 0.9165])


In [25]:
# Dummy training Example
weights = torch.ones(4 , requires_grad=True)
for epoch in range(3):
  model_output= (weights*3).sum()
  model_output.backward()

  print(weights.grad)

  weights.grad.zero_()


tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [26]:
optimizer = torch.optim.SGD([weights] , lr=0.01) # Pass weights as a list
optimizer.step()
optimizer.zero_grad()

BACKPROPAGATION ALGORITHM


In [3]:
import torch
x = torch.tensor(1.0)
y = torch.tensor(2.0)

q = torch.tensor(5.0 , requires_grad=True)
# forward pass and compute
y_hat = q + x
loss = (y_hat - y) ** 2
print(loss)
# Backward pass
loss.backward()
print(q.grad)

#update weights
# next forward


tensor(16., grad_fn=<PowBackward0>)
tensor(8.)


In [ ]:
# Gradient Descent Algorithm

In [11]:
import numpy as np
X = np.array([1 ,2,3,4] , dtype=np.float32)
Y = np.array([2,4,6,8] , dtype=np.float32)

w = 0.0

# model prediction
def forward(x):
  return w * x

# loss = MSE
def loss(y , y_predicted):
  return ((y_predicted - y)**2).mean()



# gradient
# MSE = 1/N * (w*x - y ) **2
#dl/dw = 1/N 2x (w*x - y )
def gradient(x , y , y_predictes):
  return np.dot(2*x , y_predictes - y).mean()

print(f'Prediction before training : f(5) = {forward(5):.3f}')

# Training
learning_rate = 0.01
n_iters = 10

for epoch in range(n_iters):
  # prediction = forward pass
  y_pred = forward(X)

  # loss
  l = loss(Y , y_pred)
  # Gradients
  dw = gradient(X , Y , y_pred)

  # update weights
  w -= learning_rate * dw

  if epoch % 1 == 0:
    print(f'epoch {epoch+1} : w = {w:.3f} , loss = {l:.8f}')

Prediction before training : f(5) = 0.000
epoch 1 : w = 1.200 , loss = 30.00000000
epoch 2 : w = 1.680 , loss = 4.79999924
epoch 3 : w = 1.872 , loss = 0.76800019
epoch 4 : w = 1.949 , loss = 0.12288000
epoch 5 : w = 1.980 , loss = 0.01966083
epoch 6 : w = 1.992 , loss = 0.00314574
epoch 7 : w = 1.997 , loss = 0.00050331
epoch 8 : w = 1.999 , loss = 0.00008053
epoch 9 : w = 1.999 , loss = 0.00001288
epoch 10 : w = 2.000 , loss = 0.00000206
